spring.application.name=franchise-management-api
server.servlet.context-path=/app
server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://franchise_bd_user:RgLj9eoR2ZzgBQj8Sry10QpIPfbYBYZN@dpg-d7ogaegk1i2s73fa7j90-a.oregon-postgres.render.com/franchise_bd}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:franchise_bd_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:RgLj9eoR2ZzgBQj8Sry10QpIPfbYBYZN}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0